/*
 * This file is generated by jOOQ.
 */
package practice.event.store.impl.jooq.keys


import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal

import practice.event.store.impl.jooq.tables.EventRecord
import practice.event.store.impl.jooq.tables.records.EventRecordRecord



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val EVENT_RECORD_AGGREGATE_ID_VERSION_KEY: UniqueKey<EventRecordRecord> = Internal.createUniqueKey(EventRecord.EVENT_RECORD, DSL.name("event_record_aggregate_id_version_key"), arrayOf(EventRecord.EVENT_RECORD.AGGREGATE_ID, EventRecord.EVENT_RECORD.VERSION), true)
val EVENT_RECORD_PKEY: UniqueKey<EventRecordRecord> = Internal.createUniqueKey(EventRecord.EVENT_RECORD, DSL.name("event_record_pkey"), arrayOf(EventRecord.EVENT_RECORD.ID), true)
