version: '3.7'
services:
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: event-store
      POSTGRES_USER: event-store
      POSTGRES_PASSWORD: event-store
