/*
 * This file is generated by jOOQ.
 */
package practice.event.store.persistence


import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl

import practice.event.store.persistence.tables.EventRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Public : SchemaImpl("public", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.event_record</code>.
     */
    val EVENT_RECORD: EventRecord get() = EventRecord.EVENT_RECORD

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        EventRecord.EVENT_RECORD
    )
}
