/*
 * This file is generated by jOOQ.
 */
package practice.event.store.impl.jooq.tables.references


import practice.event.store.impl.jooq.tables.EventRecord



/**
 * The table <code>public.event_record</code>.
 */
val EVENT_RECORD: EventRecord = EventRecord.EVENT_RECORD
